# Generated by Django 5.1 on 2024-09-11 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprom',
            name='response',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
